# Generated by Django 6.0 on 2025-12-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCreditData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_wallet', models.CharField(max_length=42)),
                ('amount_minted', models.FloatField()),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('status', models.CharField(default='Success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
