# Generated by Django 5.2.9 on 2026-02-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carboncreditdata_id_alter_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='biomass_credits',
            field=models.FloatField(default=0.0),
        ),
    ]
