# Generated by Django 5.2.9 on 2025-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
