# Generated by Django 5.2.9 on 2025-12-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_upload_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='model2_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='ndvi_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
